### ISSUE TITLE
TOO High

### ISSUE THREAD

**Issue by pntrader** [Romanysoft/SpeedTest#10]
The DL and UL speeds are WAY off, they are reading faster then they are.  Example, my DL speed shows 340mbps, I WISH.

**Comment by Webber2014** [comment]
Experiencing the same issue at times.

**Comment by lauer3912** [comment]
@Webber2014 Thank you for your feedback. We are refactor the code, fix the problem and improve performance

**Comment by lauer3912** [comment]
@pntrader  @Webber2014 

We would very much like to know in the end is what causes Speedtest not work. We have prepared the following steps, I hope you can help us pinpoint the problem. Sincere thanks!

1. Redownload the version 6.2.
https://github.com/Romanysoft/SpeedTest/blob/master/Publish/6.2/SpeedTest.zip

2. Open ”Applications" folder, find the "Utilities" folder, To open it:
![](https://github.com/Romanysoft/SpeedTest/blob/master/Images/Bugs/2015-11-13_222233.jpg?raw=true)

3.In "Utilities" folder, find "Console" application, To launch it:
![](https://github.com/Romanysoft/SpeedTest/blob/master/Images/Bugs/2015-11-13_222426.jpg?raw=true)


4.Then, run "Speedtest" application, You will see some information showing in the "Console" application.If you don't mind, I hope you will involve speedtest information sent to us. (app.romanysoft@gmail.com)

![](https://github.com/Romanysoft/SpeedTest/blob/master/Images/Bugs/2015-11-13_232557.jpg?raw=true)
