### ISSUE TITLE
Auto Test chrashes

### ISSUE THREAD

**Issue by Webber2014** [Romanysoft/SpeedTest#11]
When running the Auto Test modus, after several tests, the app crashes.  :-(
Tried several settings (time intervals) but issue remains.

**Comment by Webber2014** [comment]
Below the first part of the crash report:

---------------------------------------------------------------------------------------------------------------

Process:               SpeedTest [47588]
Path:                  /Applications/SpeedTest.app/Contents/MacOS/SpeedTest
Identifier:            com.romanysoft.app.macos.speedtest
Version:               5.15.02826 (1502826)
App Item ID:           721474844
App External ID:       811879079
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           SpeedTest [47588]
User ID:               502

Date/Time:             2015-04-13 17:37:48.731 +0200
OS Version:            Mac OS X 10.10.3 (14D131)
Report Version:        11
Anonymous UUID:        011FEDB4-5F30-1709-F9F0-E2E6CADC02B6


Time Awake Since Boot: 92000 seconds

Crashed Thread:        16  Dispatch queue: 1428939411026 :: NSOperation 0x60000007e3c0 (QOS: USER_INITIATED)

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000517e3fe9bec0

VM Regions Near 0x517e3fe9bec0:
    JS JIT generated code  00003054a7601000-00003054a7602000 [    4K] ---/rwx SM=NUL  
--> 
    MALLOC_NANO            0000600000000000-0000600000400000 [ 4096K] rw-/rwx SM=COW  

Application Specific Information:
objc_msgSend() selector name: release

**Comment by lauer3912** [comment]
@Webber2014 Thank you for your feedback.  We are refactor the code, fix the problem and improve performance

**Comment by Webber2014** [comment]
Great!  :+1:
