### ISSUE TITLE
Too slow

### ISSUE THREAD

**Issue by RadyAlsaygh** [Romanysoft/SpeedTest#13]
It takes about three minutes to give up results.

**Comment by lauer3912** [comment]
@RadyAlsaygh 

We would very much like to know in the end is what causes Speedtest not work. We have prepared the following steps, I hope you can help us pinpoint the problem. Sincere thanks!

1. Redownload the version 6.2.
https://github.com/Romanysoft/SpeedTest/blob/master/Publish/6.2/SpeedTest.zip

2. Open ”Applications" folder, find the "Utilities" folder, To open it:
![](https://github.com/Romanysoft/SpeedTest/blob/master/Images/Bugs/2015-11-13_222233.jpg?raw=true)

3.In "Utilities" folder, find "Console" application, To launch it:
![](https://github.com/Romanysoft/SpeedTest/blob/master/Images/Bugs/2015-11-13_222426.jpg?raw=true)


4.Then, run "Speedtest" application, You will see some information showing in the "Console" application.If you don't mind, I hope you will involve speedtest information sent to us. (app.romanysoft@gmail.com)

![](https://github.com/Romanysoft/SpeedTest/blob/master/Images/Bugs/2015-11-13_232557.jpg?raw=true)

**Comment by texsar** [comment]
I will try this when I get home. Thank you. Terry
