### ISSUE TITLE
How long is the actual test supposed to take?

### ISSUE THREAD

**Issue by jamessireno** [Romanysoft/SpeedTest#14]
First of all - my internet has been a nightmare for the past 2 months.  Completely inconsistent, and worst than that, it seems to be on and off constantly.  So I am trying to use this app as a tool to help diagnose this problem over time - but I'm not sure that it will help with tracking the drop outs.  

I am also really confused as to wether or not it is working properly to begin with.  Online speed tests seem to happen pretty quick, but running the test on the SpeedTest App (Ver 5.15.02826) seems to take around 5 minutes.  I wanted to see if that sounded about right - or if it is just yet another symptom of my crappy internet problems.  (which would be ironic if my internet was so bad it screwed up my ability to use an internet connection diagnostic tool)

BTW the last 3 readings were:

Down - 7.5 / 3.2 / 1.6
Up - 1.2 / 0.9 / 1.0

(and I am paying for 50 down / 8 Up)

**Comment by lauer3912** [comment]
@jamessireno   Version 6.2 work properly?

**Comment by texsar** [comment]
I'll have to check when I get home.

**Comment by texsar** [comment]
No, red radio Start button flashes, click on it and nothing happens. I can access the drop down menus but that’s all. Do you need screen shots? Running v6.2

**Comment by lauer3912** [comment]
@jamessireno, @texsar 

We would very much like to know in the end is what causes Speedtest not work. We have prepared the following steps, I hope you can help us pinpoint the problem. Sincere thanks!

1. Redownload the version 6.2.
https://github.com/Romanysoft/SpeedTest/blob/master/Publish/6.2/SpeedTest.zip

2. Open ”Applications" folder, find the "Utilities" folder, To open it:
![](https://github.com/Romanysoft/SpeedTest/blob/master/Images/Bugs/2015-11-13_222233.jpg?raw=true)

3.In "Utilities" folder, find "Console" application, To launch it:
![](https://github.com/Romanysoft/SpeedTest/blob/master/Images/Bugs/2015-11-13_222426.jpg?raw=true)


4.Then, run "Speedtest" application, You will see some information showing in the "Console" application.If you don't mind, I hope you will involve speedtest information sent to us. (app.romanysoft@gmail.com)

![](https://github.com/Romanysoft/SpeedTest/blob/master/Images/Bugs/2015-11-13_232557.jpg?raw=true)

**Comment by texsar** [comment]
James: I deleted my v6.2 and downloaded your trial version. The trial version actually worked. I’m using El Capitan also. Now can I get the registration key so I can use the full version? Thanks Terry

**Comment by lauer3912** [comment]
@texsar Okay, Provide an email address for me, it's best to gmail.

**Comment by texsar** [comment]
Texsar1992@gmail.com

**Comment by lauer3912** [comment]
@texsar I have informed customer send a registration code

**Comment by texsar** [comment]
Thank you James.
