### ISSUE TITLE
Updated to ver 6 and it no longer works?

### ISSUE THREAD

**Issue by Abbs69** [Romanysoft/SpeedTest#16]

**Comment by kevinwestby** [comment]
Installed v6.1, app loads, but when I click on Start.....nothing

**Comment by texsar** [comment]
Same problem as Kevin. Did you test your product before you sent out the updates?

**Comment by lauer3912** [comment]
@texsar Can you provide the log?

**Comment by texsar** [comment]
Where is it located. I don't see an log capability anywhere.

**Comment by lauer3912** [comment]
@texsar  Mac OS X version number?

**Comment by texsar** [comment]
10.9.5

**Comment by lauer3912** [comment]
@texsar, @kevinwestby  Version 6.2 work properly?

**Comment by LJBray** [comment]
Having same problem as above.
Updated to version 6.2, still same problem, click START and it stops flashing but nothing happens.
Running OS X version 10.11.1

**Comment by kevinwestby** [comment]
Still the same, v6.2 on OS X 10.11.1.....click Start, nothing happens

**Comment by lauer3912** [comment]
We would very much like to know in the end is what causes Speedtest not work. We have prepared the following steps, I hope you can help us pinpoint the problem. Sincere thanks!

1. Redownload the version 6.2.
https://github.com/Romanysoft/SpeedTest/blob/master/Publish/6.2/SpeedTest.zip

2. Open ”Applications" folder, find the "Utilities" folder, To open it:
![](https://github.com/Romanysoft/SpeedTest/blob/master/Images/Bugs/2015-11-13_222233.jpg?raw=true)

3.In "Utilities" folder, find "Console" application, To launch it:
![](https://github.com/Romanysoft/SpeedTest/blob/master/Images/Bugs/2015-11-13_222426.jpg?raw=true)


4.Then, run "Speedtest" application, You will see some information showing in the "Console" application.If you don't mind, I hope you will involve speedtest information sent to us. (app.romanysoft@gmail.com)

![](https://github.com/Romanysoft/SpeedTest/blob/master/Images/Bugs/2015-11-13_232557.jpg?raw=true)

**Comment by AngusStone** [comment]
I have exactly the same problem. It used to work, have not used it for a while and now it does not work.
OSX version 10.11.1
MacBook Pro (Retina, 13-inch, Late 2012)

[Console log when trying to use speedtest.docx](https://github.com/Romanysoft/SpeedTest/files/50734/Console.log.when.trying.to.use.speedtest.docx)

**Comment by lauer3912** [comment]
@AngusStone  

Found main issue: The "SpeedTest" service can not run.

"/Users/angusstone/Library/Containers/com.romanysoft.app.macos.speedtest/Data/Resources" 
This directory content, can help me screenshot?

**Comment by AngusStone** [comment]
I can't see that directory. angusstone does not contain a subdirectory 'Library'. At least I can't see it.

**Comment by AngusStone** [comment]
Hi,
Sorry about the earlier message - I’ve now discovered how to look at the hidden files and here is the screen shot


Regards

Angus Stone

**Comment by lauer3912** [comment]
@AngusStone I can't see screen shot.

**Comment by AngusStone** [comment]
I've dragged the file into here - let me have an alternative email where I can send the file if you still have problems seeing it.
<img width="1280" alt="screen shot 2015-12-03 at 22 07 51" src="https://cloud.githubusercontent.com/assets/16133509/11587818/2ad57e86-9a74-11e5-939f-1715530f7e00.png">
Regards 
Angus

**Comment by lauer3912** [comment]
@AngusStone  

Redownload the version 6.2.
https://github.com/Romanysoft/SpeedTest/blob/master/Publish/6.2/SpeedTest.zip

Try.

**Comment by AngusStone** [comment]
I also have an iMac.
I installed it on the iMac, from the App store and it worked fine. 
I uninstalled it from my Macbook and then 10 minutes later reinstalled it, and it does not work. The app opens, the start button flashes, I click start and the start button stops flashing and nothing happens.

**Comment by AngusStone** [comment]
I went back to the Macbook. Uninstalled it again. Emptied the trash. Restarted the Macbook. Installed it again and it still does not work. 
I noticed that when it installs from the App Store the button next to the app in the purchased list reads 'installed' but it does not change to 'open' until the app store is closed and reopened. I'm pretty sure that with other apps the button label does change to 'open'.

**Comment by lauer3912** [comment]
@AngusStone 

Try the following steps：

1. Locate the "/Users/angusstone/Library/Containers/com.romanysoft.app.macos.speedtest/Data/Resources" , to empty the directory.

2. Uninstall it and reinstall it.

3. run try.

Hope to get your good news. 
Give me a valid email address, it is best to GMail, we present a product to you.

Thank you again!

**Comment by AngusStone** [comment]
Hi,
That did it. It is now up and working again.
Thanks for your help.

**Comment by lauer3912** [comment]
@AngusStone Good news!

**Comment by LJBray** [comment]
Updating to Version 6.3 has fix the problem for me

**Comment by lauer3912** [comment]
@LJBray Thank you for your feedback

**Comment by swillman** [comment]
a minute ago I've downloaded SpeedTest first time. After opening the App and pushing the button "Start" nothing happened. Even a restart didn't help. I'm using a Mac Mini (Late 2012) 2,5Ghz 16GB OS X 10.11.3 (15D21) SpeedTest Ver.6.5. 
Should I try Ver. 6.2 as well? 
Anny sugestion / help is really appreciated.
