### ISSUE TITLE
will not test

### ISSUE THREAD

**Issue by Whyisdaddy** [Romanysoft/SpeedTest#17]
![screen shot 2016-08-08 at 10 31 51 am](https://cloud.githubusercontent.com/assets/4367006/17483275/603d29a0-5d53-11e6-9848-04a8430f9acd.png)
I have been waiting for almost 35 minutes and when I click test all I get is a message saying
"Please wait , Configuring the speed test engine."
and that's all it will do.
It don't test anything.

**Comment by lauer3912** [comment]
Mac App Store Version?

> We are developing Version 6.6 should be able to solve your problem.
![2016-08-09_113914](https://cloud.githubusercontent.com/assets/1635018/17503861/f0306644-5e25-11e6-9b3c-1db86a160bca.png)
