### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by raulpadron** [Romanysoft/SpeedTest#2]
Hi friends!

Your SpeedTest application is great. 

Unfortunately in my country internet speed is so slow that I can not use it. Please add -if possible- a toggle switch to use a maximum speed of lets say 5 Mbits/s o better an adjustable maximum speed. 

Best regards

Raul Padron

**Comment by raulpadron** [comment]
I am glad to say that the version 5.15.02826 is now displaying the ping, download and upload values. However the values are too high: my connection is 56 ms, 1.84 Mbps download and 0.58 Mbps uploading by the SpeedTest application reports 116.57 ms, 11.76 Mbps and 1.44 Mbps. Any idea what happen? Could be good idea to show the server used for the measurement, so the user can compare with other speed test software. Thanks in advance and congrats again. Raul

**Comment by lauer3912** [comment]
This upgrade has a bug, will actually test out the download speed, upload speed has expanded four times. This is a developer writing error, back, we upgrade to fix the problem as soon as possible. Thank you very much for your feedback!

**Comment by raulpadron** [comment]
Your are wellcome. Congratulations again!
BlackBerry-Movilnet

-----Original Message-----
