### ISSUE TITLE
Can't open the Speed Test program

### ISSUE THREAD

**Issue by MasonRose** [Romanysoft/SpeedTest#20]
When I open it.  I get these options: "Trial times has over 3, please register."  I have already registered and paid my $5.99 fee. Then 3 choices "Cancel  Buy   Register"  Cancel: cancels this page.  Buy:  Register: Register gets: "Register failed"  "Invalid License"  OK

So right now I can't use Speed Test.  Please help me!

mason.c.rose@gmail.com.

**Comment by lauer3912** [comment]
A license can register up to four clients, more clients, please purchase a new license.

**Comment by lauer3912** [comment]
Send new license to you
