### ISSUE TITLE
Lack of support

### ISSUE THREAD

**Issue by MasonRose** [Romanysoft/SpeedTest#21]
I can't use speed test now.  Even though I have registered and paid my 5.99 fee.  See below

Can someone just email me with the solution.  this is frustrating.

mason.c.rose@gmail.com

**Comment by lauer3912** [comment]
A license can register up to four clients, more clients, please purchase a new license.

**Comment by MasonRose** [comment]
On 8/15/16 I paid $6.36 to DRI*SPEEDTEST FOR MAC MINNETONKA MN.  I thought this was to upgrade to the latest version.  What was that for?   You now tell me that I have to purchase a "new License"   I don't have any "clients" What does this mean "A license can register up to four clients, more clients, please purchase a new license."?  Do I have a "License" already?  Why do I need a new one.

Can I get my money back and just go back to the Version I had originally? 

Mason

**Comment by lauer3912** [comment]
Send new license to you
