### ISSUE TITLE
I'm not sure how to read the scales, the only one that is high is the ping scale .  The download scale is only 4.13 is that  what t's suppose to be?

### ISSUE THREAD

**Issue by mrsdmr** [Romanysoft/SpeedTest#5]

**Comment by Maso69** [comment]
Whats an avge speed supposed to be for the ping scale, download and upload?

**Comment by Maso69** [comment]
![screen shot 2016-07-05 at 1 37 36 pm](https://cloud.githubusercontent.com/assets/20292533/16573462/8ebc7cb0-42b7-11e6-90a6-bd81a9fde68e.png)

**Comment by lauer3912** [comment]
@Maso69 ?
