### ISSUE TITLE
Ability to schedule

### ISSUE THREAD

**Issue by kevinwestby** [Romanysoft/SpeedTest#7]
If this app could be configured to run on a scheduled basis....it would be killer!!  Any plans in that area?

**Comment by kevinwestby** [comment]
The latest version is working now, but this feature appears to have been removed.  Any plans to re-add it?

**Comment by lauer3912** [comment]
@kevinwestby Due to the previous version on most of the user's machine not work properly. Although version 6.3 received feedback, has solved the most problems. But, still, to temporarily add scheduling feature, is no plan to add it back soon.
