### ISSUE TITLE
Speed measured is too low.

### ISSUE THREAD

**Issue by poplloy** [Romanysoft/SpeedTest#8]
I have an internet connection rated at 60 Mbps.  The first time i ran SpeedTest, the download speed was close to 60. Ever since it has given the results of around 10 Mbps or lower.  I have run speediest.net and it gives close to 60 Mbps and a program on my iPad  with the same results.  Is there a configuration toggle I have missed?

Also, every time I start the program I am asked to I am asked to rate the app. I find this quite annoying...

Thanx,
Lloy

**Comment by Kiwigrue** [comment]
I am experiencing a similar problem which commenced and continues to persist since I upgraded to the latest version

Cheers
Alistair

**Comment by lauer3912** [comment]
@Kiwigrue @poplloy   New version 5.15.01826 is published...  you can try it again!

**Comment by poplloy** [comment]
Hi,
The new update made no difference...
Thanx...

**Comment by Kiwigrue** [comment]
Agree … my experience was exactly the same … no difference


Cheers

A l i s t a i r  S p e n c e
- - - - - - - - - - - - - - - - - - - - - -
iPhone: +64 21 839 342 - Voice: +64 9 376 8117 -   alistairspence@mac.com

**Comment by poplloy** [comment]
New update has not fixed the speed issue...thanx...

**Comment by Kiwigrue** [comment]
I agree … no different still recording too low a speed/s!

Something fundamental changed in the updated version early December 2014 that was different from the earlier versions (sampling methodology or process?)

Cheers
Alistair


A l i s t a i r  S p e n c e
- - - - - - - - - - - - - - - - - - - - - -
iPhone: +64 21 839 342 - Voice: +64 9 376 8117 -   alistairspence@mac.com

**Comment by JMGPhila** [comment]
1.6 Down? HA! I am opening pages before I finish clicking my mouse. I am downloading 1gb files in seconds. Junk as I figured I would get. Next time I will trust why there are 2 1/2 stars.

**Comment by JMGPhila** [comment]
Speedtest.verizon.net 87mb/s. Why didn't I just go there to begin with?

**Comment by maykie91** [comment]
I'm a new user of SpeedTest for OSX app but I'm not very satisfy with measurments outputs from your app. I have a max download limit 20 Mbit/s from my provider.  When I'm using your application for internet conection testing there is a lot of inaccurate results outputs. In most cases is more then 30 Mbits/s even there was also 80 Mbit/s !! Of course that I compared it with others web based speed test server and there was no problem in measurments. At this moment your app is useless !! There is a lot of issues about this problem on your forum page!  Please try to do something for us! Than we will be very grateful.  Thanxs for prompt response.

**Comment by lauer3912** [comment]
@maykie91  This upgrade has a bug, will actually test out the download speed, upload speed has expanded four times. This is a developer writing error, back, we upgrade to fix the problem as soon as possible. Thank you very much for your feedback!
